// Top-level build file where you can add configuration options common to all sub-projects/modules.

//plugins {
//    alias(libs.plugins.android.application)
//    alias(libs.plugins.google.services)
//    alias(libs.plugins.kotlin.android)
//}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath libs.gradle
        classpath libs.google.services
        classpath libs.kotlin.gradle.plugin
        classpath libs.kotlin.compose.compiler
        classpath libs.firebase.crashlytics.gradle
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
