apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'kotlin-kapt'

def keystorePropertiesFile = rootProject.file('keystore.properties')
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    if (keystorePropertiesFile.exists()) {
        signingConfigs {
            config {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }
    defaultConfig {
        applicationId "com.capstone.nik.mixology"
        targetSdkVersion 35
        compileSdk 35
        minSdkVersion 23
        versionCode 14
        versionName "1.14"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        if (keystorePropertiesFile.exists()) {
            signingConfig signingConfigs.config
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.config
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    namespace 'com.capstone.nik.mixology'
    buildFeatures {
        buildConfig true
        compose true
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation libs.appcompat
    implementation libs.cardview
    implementation libs.recyclerview
    implementation libs.gridlayout
    implementation libs.coordinatorlayout
    implementation libs.legacy.support.v4
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.lifecycle.viewmodel.compose
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.runtime.compose
    implementation libs.material
    implementation libs.kotlinx.coroutines.android
    implementation libs.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.compose.material3.window.size
    implementation libs.compose.material.icons.extended
    implementation libs.navigation.compose
    implementation libs.coil.compose
    debugImplementation libs.compose.ui.tooling

    implementation libs.retrofit
    implementation libs.converter.gson

    implementation libs.picasso
    implementation libs.circleimageview

    implementation libs.appcompat.resources

    implementation libs.play.services.auth

    implementation libs.dagger
    implementation libs.javax.inject
    implementation libs.core.ktx

    compileOnly libs.jsr250.api
    kapt libs.dagger.compiler

    implementation libs.fragment
    implementation libs.fragment.ktx
    debugImplementation libs.fragment.testing

    implementation libs.androidx.room.runtime
    implementation libs.androidx.room.ktx
    kapt libs.androidx.room.compiler

    implementation platform(libs.firebase.bom)
    implementation libs.firebase.crashlytics
    implementation libs.firebase.analytics

    testImplementation libs.junit
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
